// Host-side driver for the sub-reasoner invocations of EYE's graph-scoped
// builtins (log:collectAllIn, log:forAllIn, log:ifThenElseIn, log:conclusion,
// log:satisfiable, e:call, e:fail and e:findall).
//
// Native EYE evaluates these builtins by spawning a fresh `eye` process
// (exec/2 -> shell/2) that computes the deductive closure of the scope graph
// in isolation. Under Emscripten there is no shell, so the pvm generated by
// scripts/generate-pvm.ts redefines exec/2 to yield the command line to the
// JavaScript host with await/2 instead. The callback produced by
// bridgeCallback/2 answers those yields by booting a fresh swipl-wasm module
// with the same reasoner image (the isolation analogue of the process spawn),
// copying the temporary input files across, running the sub-query, and
// writing the captured stdout to the redirect target of the requesting
// instance. See https://github.com/eyereasoner/eye-js/issues/873.
import type { SWIPLModule } from 'swipl-wasm';
import { qaQuery } from './query';

/** Prefix of the requests yielded by the exec/2 bridge in the generated pvm */
export const EXEC_REQUEST_PREFIX = 'eyejs:exec ';

/** Boots a fresh SWIPL module preloaded with a reasoner image */
export type SwiplLoader = (options?: Partial<EmscriptenModule>) => Promise<SWIPLModule>;

export interface BridgeOptions {
  /**
   * Loader used to boot the fresh sub-reasoner modules; it should load the
   * same image as the module the callback is attached to
   */
  spawn: SwiplLoader;
  /** Callback answering the remaining (non-exec) yields, i.e. log:ask questions */
  cb?: (res: string) => Promise<string>;
}

interface ExecRequest {
  /** The argv of the sub-reasoner, without the leading program name */
  args: string[];
  /** The file that the command line redirects stdout to */
  outputFile: string;
}

interface SubRunResult {
  /** Whether the sub-reasoner completed with exit code 0 */
  ok: boolean;
  stdout: string;
  stderr: string;
}

/**
 * Parses the command line that exec/2 was asked to run. eye.pl builds the
 * sub-reasoner command lines as
 *   `eye --nope [--quiet] <TmpData> --query <TmpQuery> > <TmpOut>` or
 *   `eye --nope [--quiet] <TmpData> --pass-all > <TmpOut> 2> /dev/null`;
 * anything else (in particular the arbitrary shell commands of e:exec) is not
 * supported in the WASM build.
 */
function parseExecRequest(command: string): ExecRequest | undefined {
  const tokens = command.trim().split(/\s+/);
  const redirect = tokens.indexOf('>');
  if (tokens[0] !== 'eye' || redirect === -1 || !tokens[redirect + 1]) {
    return undefined;
  }
  return { args: tokens.slice(1, redirect), outputFile: tokens[redirect + 1] };
}

/**
 * eye.pl numbers the anonymous variables it writes into the temporary input
 * files with a process-wide counter, so the two otherwise identical
 * sub-reasoner invocations of a scope evaluation differ in variable
 * numbering (`?_7102` vs `?_13330`). Renaming the variables in order of
 * first appearance maps alpha-equivalent inputs onto the same cache key
 * while keeping distinct variable structures distinct.
 */
function canonicalizeVariables(content: string): string {
  const seen = new Map<string, string>();
  return content.replace(/\?_\d+/g, (name) => {
    let canonical = seen.get(name);
    if (!canonical) {
      canonical = `?_v${seen.size}`;
      seen.set(name, canonical);
    }
    return canonical;
  });
}

/**
 * Cache key for a sub-reasoner invocation. EYE issues the sub-reasoner call
 * for a scope twice per evaluation, under fresh temporary file names, so the
 * key is built from the argument structure and the (variable-canonicalized)
 * input file *contents* rather than their paths.
 */
function requestKey(module: SWIPLModule, args: string[]): string {
  return JSON.stringify(args.map((arg) => (arg.startsWith('-')
    ? arg
    : { file: canonicalizeVariables(module.FS.readFile(arg, { encoding: 'utf8' })) })));
}

async function runSubReasoner(
  module: SWIPLModule,
  options: BridgeOptions,
  args: string[],
): Promise<SubRunResult> {
  let stdout = '';
  const stderr: string[] = [];
  const child = await options.spawn({
    print: (str: string) => { stdout += `${str}\n`; },
    printErr: (str: string) => { stderr.push(str); },
  });

  const childArgs: string[] = [];
  for (let i = 0; i < args.length; i += 1) {
    if (args[i].startsWith('-')) {
      childArgs.push(args[i]);
    } else {
      // Copy the temporary file prepared by the requesting reasoner into the
      // filesystem of the fresh module
      const name = `sub_input_${i}.n3s`;
      child.FS.writeFile(name, module.FS.readFile(args[i]));
      childArgs.push(name);
    }
  }

  // The sub-reasoner gets the same driver, so that scoped builtins nested
  // inside scope graphs recursively get fresh instances of their own
  // eslint-disable-next-line no-use-before-define
  await qaQuery(child, 'main', childArgs, bridgeCallback(child, options));

  // eye.pl's main/1 traps halt/1 and records the would-be exit code in the
  // exit_code global instead (0 on success, e.g. 2 on inference fuse)
  const status = child.prolog.query('nb_getval(exit_code, Code).').once() as { Code?: unknown };
  return { ok: status.Code === 0, stdout, stderr: stderr.join('\n') };
}

/**
 * Creates a yield callback for the async query loop (qaQuery) that answers
 * the exec/2 requests of the WASM reasoner image by running the requested
 * sub-reasoner on a fresh module, and forwards any other yield (log:ask
 * questions) to the provided cb.
 * @param module The module the callback answers the requests of
 * @param options The bridge options
 *  - spawn: loader booting fresh modules with the same reasoner image
 *  - cb: A callback to be used for question/answering (default: undefined)
 * @returns The callback to drive qaQuery with
 */
export function bridgeCallback(
  module: SWIPLModule,
  options: BridgeOptions,
): (request: string) => Promise<string> {
  // EYE issues each scope's sub-reasoner invocation twice with identical
  // inputs per evaluation; cache on contents so the repeat is free
  const cache = new Map<string, Promise<SubRunResult>>();

  return async (request: string): Promise<string> => {
    if (!request.startsWith(EXEC_REQUEST_PREFIX)) {
      if (options.cb) {
        return options.cb(request);
      }
      throw new Error(`The reasoner yielded a question [${request}] but no cb option was provided to answer it`);
    }

    const parsed = parseExecRequest(request.slice(EXEC_REQUEST_PREFIX.length));
    if (!parsed) {
      // Reaches exec/2 in the image, which raises it as an exec_error
      return 'eye-js: e:exec and other arbitrary shell commands are not supported in the WASM build; '
        + 'only the eye sub-reasoner invocations of the graph-scoped builtins are bridged '
        + '(see https://github.com/eyereasoner/eye-js/issues/873)';
    }

    try {
      const key = requestKey(module, parsed.args);
      let run = cache.get(key);
      if (!run) {
        run = runSubReasoner(module, options, parsed.args);
        cache.set(key, run);
      }
      const { ok, stdout, stderr } = await run;
      // Take the role of the shell redirect: expose the output of the
      // sub-reasoner at the location the requesting instance will parse
      module.FS.writeFile(parsed.outputFile, stdout);
      return ok ? 'ok' : `eye-js: sub-reasoner exited with an error: ${stderr}`;
    } catch (error) {
      return `eye-js: sub-reasoner run failed: ${error}`;
    }
  };
}
