import fs from 'fs';
import path from 'path';
import { generateImageFileString } from 'swipl-wasm/dist/generateImage';

const nm = process.argv.find((name) => name.startsWith('--name='))?.slice(7).split('.')[0] ?? 'eye';

/**
 * Prolog snippet appended to the fetched reasoner source before the image is
 * saved with qsave_program.
 *
 * The graph-scoped builtins of EYE (log:collectAllIn, log:forAllIn,
 * log:ifThenElseIn, log:conclusion, log:satisfiable, e:call, e:fail and
 * e:findall) compute the deductive closure of their scope graph by spawning a
 * fresh `eye` sub-process through exec/2 -> shell/2, which is unavailable
 * under Emscripten (see https://github.com/eyereasoner/eye-js/issues/873).
 *
 * This snippet redefines exec/2 to instead yield the command line to the
 * JavaScript host with await/2 - the same mechanism eye.pl already uses for
 * log:ask (userInput/2). The host runs the sub-reasoner on a fresh swipl-wasm
 * module (the isolation analogue of the process spawn), writes the captured
 * stdout to the redirect target inside this instance's filesystem, and
 * resumes with "ok" (see lib/bridge.ts). Any other response is raised as an
 * exec_error, mirroring the non-zero-exit behaviour of the native exec/2; the
 * scoped builtins wrap exec/2 in catch/3 and treat that as failure.
 *
 * Because the image is generated by running the source inside swipl-wasm,
 * the emscripten conditional is live at consult time and the redefinition is
 * compiled into the saved state. Native builds are unaffected.
 */
const WASM_EXEC_BRIDGE = `
% Appended by eye-js (scripts/generate-pvm.ts).
% Bridge the sub-reasoner invocations of the graph-scoped builtins to the
% JavaScript host, which cannot shell out but can boot a fresh swipl-wasm
% module instead. See https://github.com/eyereasoner/eye-js/issues/873.
:- if(current_prolog_flag(emscripten, true)).
:- abolish(exec/2).
exec(Command, 0) :-
    atomic_list_concat(['eyejs:exec ', Command], Request),
    await(Request, Response),
    (   Response == "ok"
    ->  true
    ;   throw(exec_error(Response))
    ).
:- endif.
`;

/**
 * Appends the WASM exec/2 bridge to reasoner sources that define the exec/2
 * helper (eye.pl does; lingua.pl does not shell out and is left untouched).
 */
export function withWasmExecBridge(source: string): string {
  return /^exec\(A, B\) :-$/m.test(source) ? `${source}${WASM_EXEC_BRIDGE}` : source;
}

async function main() {
  const EYE_URL = JSON.parse(fs.readFileSync(path.join(__dirname, '..', 'package.json')).toString()).config[nm].url;
  const releaseInfo = (await (await fetch(EYE_URL)).json());
  const source = await (await fetch(`https://raw.githubusercontent.com/eyereasoner/${nm}/${releaseInfo.tag_name}/${nm.split('-')[0]}.pl`)).text();
  fs.writeFileSync(
    path.join(__dirname, '..', 'lib', `${nm}.ts`),
    await generateImageFileString(withWasmExecBridge(source)),
  );
}

main();
