name: "Deploy Bundled Release"

on:
  create

jobs:
  tagged-release:
    # Don't run on releases/tags/* which causes recursive behaviour
    if: startsWith(github.ref, 'refs/tags/')
    name: "Tagged Release"
    runs-on: "ubuntu-latest"
    steps:
     - run: |
        npm ci
        npm run bundle:webpack -- --name=${{ github.ref_name }}
        npm run bundle:latest -- --name=${{ github.ref_name }}
