name: "Deploy Bundled Release"

on:
  create

jobs:
  tagged-release:
    # Don't run on releases/tags/* which causes recursive behaviour
    if: startsWith(github.ref, 'refs/tags/')
    name: "Deploy Bundled Release"
    runs-on: "ubuntu-latest"
    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.GH_TOKEN }}
      - name: Create latest bundle and add to github pages
        run: |
          # Build the latest bundle
          npm ci
          npm run bundle:webpack -- --name=${{ github.ref_name }}
          npm run bundle:latest -- --name=${{ github.ref_name }}

          # Configure Git
          git config --global user.name 'Jesse Wright'
          git config --global user.email '63333554+jeswr@users.noreply.github.com'
          
          # Move the latest bundle changes onto the pages branch and push
          git add -f bundle/
          git fetch origin origin/pages
          git checkout -t origin/pages
          git commit -m "feat: add bundle for ${{ github.ref_name }}"
          git push -u origin pages
    env:
      GH_TOKEN: ${{ secrets.GH_TOKEN }}
